[project]
name = "vit-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.11.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "numpy==1.26.4",
    "torch>=2.9.1",
]
